apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb-backup.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mongodb-backup.name" . }}
    helm.sh/chart: {{ include "mongodb-backup.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  mongo-password: {{ .Values.mongoPassword | b64enc | quote }}
